<img src="https://github.com/Ch3ddarr/DSB-Unit-02/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# EDA with `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a data set at a high level with `pandas`.

### Notebook Guide
- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Exporting data
- Conclusions and Takeaways

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

This notebook will showcase some fundamental `pandas` features and commands and in notebook 3, you will answer some questions about the data, and therefore the business question, on your own.

## Loading a CSV into a `DataFrame`

In [2]:
import pandas as pd

We'll read in the data. The `read_csv` method has lots of options, but the defaults are usually a good place to start.

In [3]:
lego = pd.read_csv("https://raw.githubusercontent.com/Ch3ddarr/DSB-Unit-02/refs/heads/main/data/lego.csv")

Let's look at the data!

In [4]:
lego.head(5)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN

# Column Operations
---

There are some columns we don't need, such as how many users on a specific platform claim to own each set. Let's remove the "Owned" column.

In [5]:
lego.drop(columns=['Owned'])

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,0.0,5.99,NaN,NaN
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,0.0,5.99,NaN,NaN
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,0.0,5.99,NaN,NaN
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,0.0,5.99,NaN,NaN
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,0.0,5.99,NaN,NaN

OK let's take a look at the data again

In [6]:
lego.head(5)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN

What?! The `Owned` column is still there, but we saw it disappear above!

This is because `pandas` operations almost always return a **copy** of the data without changing the underlying data set.

To make an operation permanent, you need to explicitly overwrite your `DataFrame` object:

In [7]:
#lego.drop(columns=['Owned'], inplace=True)
lego.head(5)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN

Let's limit our data to only the most recent sets, say the last 10 years.

To do this we will:

- calculate the age of each set
- filter out anything older than 10 years

To create new columns, we can perform a vectorized operation on the entire column (not loop through its values):

In [12]:
lego[lego['Year']>2016]

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
11436,10255-1,Assembly Square,2017,Creator Expert,Model making,Modular Buildings Collection,Normal,Box,2,LEGO exclusive,4002.0,9.0,26028.0,4.4,299.99,20.0,299.9500
11437,10256-1,Taj Mahal,2017,Creator Expert,Model making,Landmarks,Normal,Box,2,LEGO exclusive,5923.0,NaN,4384.0,4.0,369.99,3.0,404.9910
11438,10257-1,Carousel,2017,Creator Expert,Model making,Fairground Collection,Normal,Box,2,LEGO exclusive,2670.0,7.0,8752.0,4.2,199.99,12.0,440.0000
11439,10258-1,London Bus,2017,Creator Expert,Model making,Vehicles,Normal,Box,2,LEGO exclusive,1686.0,NaN,12204.0,4.2,139.99,12.0,121.4910
11440,10259-1,Winter Village Station,2017,Creator Expert,Model making,Winter Village Collection,Normal,Box,4,LEGO exclusive,902.0,5.0,12718.0,3.9,79.99,27.0,203.6194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,88.0,0.0,5.99,NaN,NaN
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,107.0,0.0,5.99,NaN,NaN

To create a new column, we use syntax similar to adding a key to a dictionary

In [14]:
lego['YearsOld'] = 2026 - lego['Year']
lego['YearsOld']

0        51
1        51
2        51
3        51
4        51
         ..
14931     3
14932     3
14933     3
14934     3
14935     3
Name: YearsOld, Length: 14936, dtype: int64

#### Reflection

How is this different from working with Python types, like numbers or lists?

---

When we look at the data, our new column will be at the end

In [15]:
lego.head(5)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,YearsOld
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN,51
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN,51
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN,51
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN,51
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN,51

We can select multiple columns to verify the new age column. To do this, pass a list instead of a single column name.

In [17]:
lego.columns

Index(['Set_ID', 'Name', 'Year', 'Theme', 'Theme_Group', 'Subtheme',
       'Category', 'Packaging', 'Num_Instructions', 'Availability', 'Pieces',
       'Minifigures', 'Owned', 'Rating', 'USD_MSRP', 'Total_Quantity',
       'Current_Price', 'YearsOld'],
      dtype='object')

# Filtering
---

Now, we can use our new column to find only the newest sets.

To filter a `DataFrame` we need:

1. A filter to apply (like a `WHERE` clause in SQL)
2. To apply this filter to the `DataFrame`

With `pandas`, even boolean operations are vectorized!

We can save that filter into a variable, then use it to index the `DataFrame`

We can also combine those steps (you'll see this a lot)

We could also save this filtered version into a new `DataFrame` variable

This is a copy, so changes to this `DataFrame` **do not affect the original `DataFrame`** but if we tried to make any changes to it we'll get a warning

This warning is just a reminder that:

- `filtered` is a "slice" of the original `lego` `DataFrame`
- it is a **copy**, so any changes to `filtered` **will not affect** `lego`

To make this go away, you can be explicit about the fact that we are copying data:

No warning!

### Multiple Filters

What about only looking at new sets that have a Star Wars theme?

To combine multiple filters:

1. Each filter needs to be parenthesized
2. Instead of Python's `and` we use `&` and instead of `or` we use `|`

In [18]:
lego[(lego["YearsOld"] < 10) & (lego["Theme"] == "Star Wars")]

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,YearsOld
11542,30496-1,U-Wing Fighter,2017,Star Wars,Licensed,Rogue One,Normal,Polybag,2,{Not specified},55.0,NaN,4409.0,3.6,NaN,13.0,4.4793,9
11543,30497-1,First Order Heavy Assault Walker,2017,Star Wars,Licensed,The Last Jedi,Normal,Polybag,2,{Not specified},54.0,NaN,7684.0,3.6,NaN,29.0,5.9687,9
11554,30611-1,R2-D2,2017,Star Wars,Licensed,Promotional,Normal,Polybag,2,LEGO exclusive,70.0,NaN,9053.0,4.0,NaN,77.0,20.0000,9
11578,40176-1,Scarif Stormtrooper,2017,Star Wars,Licensed,Rogue One,Normal,Polybag,1,LEGO exclusive,25.0,1.0,7960.0,4.0,NaN,40.0,25.0000,9
11609,40268-1,R3-M2,2017,Star Wars,Licensed,Rogue One,Normal,Polybag,2,Promotional,21.0,1.0,8239.0,3.9,NaN,42.0,7.8000,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14829,75366-1,Advent Calendar,2023,Star Wars,Licensed,NaN,Normal,{Not specified},0,{Not specified},NaN,NaN,NaN,0.0,NaN,NaN,NaN,3
14830,75368-1,{?},2023,Star Wars,Licensed,NaN,Normal,{Not specified},0,{Not specified},NaN,NaN,NaN,0.0,NaN,NaN,NaN,3
14831,75369-1,{?},2023,Star Wars,Licensed,NaN,Normal,{Not specified},0,{Not specified},NaN,NaN,NaN,0.0,NaN,NaN,NaN,3
14832,75370-1,{?},2023,Star Wars,Licensed,NaN,Normal,{Not specified},0,{Not specified},NaN,NaN,NaN,0.0,NaN,NaN,NaN,3
14833,75371-1,{?},2023,Star Wars,Licensed,NaN,Normal,{Not specified},0,{Not specified},NaN,NaN,NaN,0.0,NaN,NaN,NaN,3

In [19]:
lego[(lego["YearsOld"] < 10) | (lego["Theme"] == "Star Wars")]

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,YearsOld
3541,7101-1,Lightsaber Duel,1999,Star Wars,Licensed,Episode I,Normal,Box,1,Retail,52.0,2.0,10759.0,3.6,NaN,9.0,85.00,27
3542,7110-1,Landspeeder,1999,Star Wars,Licensed,Episode IV,Normal,Box,1,Retail,49.0,2.0,12190.0,3.7,NaN,7.0,75.00,27
3543,7111-1,Droid Fighter,1999,Star Wars,Licensed,Episode I,Normal,Box,1,Retail,62.0,NaN,10407.0,3.4,NaN,6.0,30.00,27
3544,7121-1,Naboo Swamp,1999,Star Wars,Licensed,Episode I,Normal,Box,1,Retail,82.0,4.0,9568.0,3.6,NaN,9.0,45.00,27
3545,7128-1,Speeder Bikes,1999,Star Wars,Licensed,Episode VI,Normal,Box,1,Retail,93.0,3.0,11657.0,4.1,NaN,2.0,128.25,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN,3
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,88.0,0.0,5.99,NaN,NaN,3
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,107.0,0.0,5.99,NaN,NaN,3

# Sorting
---

Let's find the most expensive LEGO sets. To do this, we need to sort our data.

Sorting is done by calling `.sort_values()` on the `DataFrame` and specifying the column.

In [22]:
lego.sort_values(by='USD_MSRP')

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,YearsOld
7382,852461-1,Gift Tag Stickers,2008,Gear,Miscellaneous,Seasonal,Gear,{Not specified},0,{Not specified},NaN,NaN,16.0,0.0,1.49,NaN,NaN,18
12045,30541-1,Animal Free Builds - Make It Yours,2018,Miscellaneous,Miscellaneous,Make It Yours,Normal,Polybag,2,LEGO exclusive,10.0,NaN,1103.0,3.6,1.99,17.0,3.40,8
8139,8683-3,Caveman,2010,Collectable Minifigures,Miscellaneous,Series 1,Normal,Foil pack,0,Retail,6.0,1.0,7496.0,3.9,1.99,NaN,NaN,16
8137,8683-1,Tribal Hunter,2010,Collectable Minifigures,Miscellaneous,Series 1,Normal,Foil pack,2,Retail,9.0,1.0,6134.0,3.7,1.99,0.0,NaN,16
8148,8683-12,Ninja,2010,Collectable Minifigures,Miscellaneous,Series 1,Normal,Foil pack,0,Retail,7.0,1.0,6941.0,3.6,1.99,NaN,NaN,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14922,662302-1,"Cave Explorer, Creeper and Slime",2023,Minecraft,Licensed,Magazine Gift,Other,Foil pack,0,Retail - limited,30.0,2.0,226.0,0.0,NaN,1.0,7.00,3
14923,662303-1,Adventurer with Drowned and Axolotl,2023,Minecraft,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,NaN,NaN,54.0,0.0,NaN,0.0,NaN,3
14924,662309-1,Knight with Chest and Anvil,2023,Minecraft,Licensed,Magazine Gift,Other,Foil pack,0,Retail - limited,17.0,1.0,261.0,0.0,NaN,0.0,NaN,3
14925,682303-1,Miles Morales,2023,Marvel Super Heroes,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,8.0,1.0,563.0,0.0,NaN,2.0,6.95,3
14926,682304-1,Green Goblin,2023,Marvel Super Heroes,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,19.0,1.0,132.0,0.0,NaN,0.0,NaN,3

The default is ascending order, so to sort in descending order we specify `ascending=False`

In [23]:
lego.sort_values(by='USD_MSRP', ascending=False)

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price,YearsOld
11928,75192-1,Millennium Falcon,2017,Star Wars,Licensed,Ultimate Collector Series,Normal,Box,11,LEGO exclusive,7541.0,8.0,18898.0,4.6,849.99,10.0,700.00,9
12854,75252-1,Imperial Star Destroyer,2019,Star Wars,Licensed,Ultimate Collector Series,Normal,Box,10,LEGO exclusive,4784.0,2.0,8219.0,4.4,699.99,28.0,970.00,7
13449,10294-1,Titanic,2021,Icons,Model making,Miscellaneous,Normal,Box,27,LEGO exclusive,9090.0,NaN,3994.0,4.6,679.99,8.0,640.00,5
13946,10307-1,Eiffel Tower,2022,Icons,Model making,Landmarks,Normal,Box,21,LEGO exclusive,10001.0,NaN,1825.0,4.2,629.99,1.0,624.99,4
14380,75331-1,The Razor Crest,2022,Star Wars,Licensed,Ultimate Collector Series,Normal,Box,13,LEGO exclusive,6187.0,4.0,2732.0,4.7,599.99,3.0,450.00,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14922,662302-1,"Cave Explorer, Creeper and Slime",2023,Minecraft,Licensed,Magazine Gift,Other,Foil pack,0,Retail - limited,30.0,2.0,226.0,0.0,NaN,1.0,7.00,3
14923,662303-1,Adventurer with Drowned and Axolotl,2023,Minecraft,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,NaN,NaN,54.0,0.0,NaN,0.0,NaN,3
14924,662309-1,Knight with Chest and Anvil,2023,Minecraft,Licensed,Magazine Gift,Other,Foil pack,0,Retail - limited,17.0,1.0,261.0,0.0,NaN,0.0,NaN,3
14925,682303-1,Miles Morales,2023,Marvel Super Heroes,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,8.0,1.0,563.0,0.0,NaN,2.0,6.95,3
14926,682304-1,Green Goblin,2023,Marvel Super Heroes,Licensed,Magazine Gift,Other,Paper bag,0,Retail - limited,19.0,1.0,132.0,0.0,NaN,0.0,NaN,3

# Exporting data
---

For now, we will report to our stakeholders that Star Wars sets seem to command high prices. We will export the most recent Star Wars sets to a separate `DataFrame`

`pandas` also supports many *export* formats, like CSVs

# Conclusions and Takeaways
---

- `pandas` is the most popular data analysis library in the Python ecosystem
- `pandas` introduces the `Series` and `DataFrame` types to make manipulating data easier
- `pandas` uses vectorized operations to manipulate entire columns at once
- most operations return *copies* of the data, so users must be explicit when overwriting their data

#### Reflect

Make sure you understand:

- why working with `pandas` is more efficient than working with Python objects like lists
- what the difference between a `DataFrame` and a `Series` is
- that most of the time `pandas` operations return **copies** of the data